env: # Environment variables to pass to all tasks
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"

    rclone_config: "ENCRYPTED[6fd591d0c10033e479b128018750feb4e7b81da07bba5af3fd2335ff43f6c0925a40fa719c46f564a5cb98701a61078c]"

task:
    name: PixelExperience
    timeout_in: 120m
    container:
      image: apon77/aosp:latest
      cpu: 8
      memory: 32G
    download_ccache_background_script:
      - set -evx
      - command=$(head /tmp/ci/ccache.sh -n $(expr $(grep upload /tmp/ci/ccache.sh -n | cut -f1 -d:) - 1))
      - bash -c "$command"
    sync_script:
      - set -evx
      - command=$(head /tmp/ci/build.sh -n $(expr $(grep "# build" /tmp/ci/build.sh -n | cut -f1 -d:) - 1))
      - bash -c "$command"
    monitor_background_script:
      - ./monitor
    build_script:
      - set -evx
      - command=$(tail /tmp/ci/build.sh -n +$(expr $(grep "# build" /tmp/ci/build.sh -n | cut -f1 -d:) + 2) | head -n -16)
      - bash -c "$command"
    upload_rom_script:
      - set -evx
      - command=$(tail /tmp/ci/build.sh -n +$(expr $(grep "# upload" /tmp/ci/build.sh -n | cut -f1 -d:) + 2))
      - bash -c "$command"
    upload_ccache_script:
      - set -evx
      - command=$(tail /tmp/ci/ccache.sh -n +$(expr $(grep "# upload" /tmp/ci/ccache.sh -n | cut -f1 -d:) + 2))
      - bash -c "$command"
